export const incidents = [
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },

  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },

  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },

  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
  {
    id: "INC-2026-001",
    title: "Database Service Down",
    service: "Database Service",
    severity: "High",
    status: "Investigating",
    assignee: "Riya",
    createdAt: "2026-01-01 10:00:00",
  },
];
